apiVersion: v1
kind: Namespace
metadata:
  name: vulnes 
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: vulnes 
  name: cve-2024-3094
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cve-2024-3094
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cve-2024-3094
    spec:
      containers:
      - image: shefirot/vulnerable:cve-2024-3094
        imagePullPolicy: Always
        name: cve-2024-3094
        ports:
        - containerPort: 22
        securityContext:
            privileged: true
